/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as StationsStationIDImport } from './routes/stations/$stationID'
import { Route as ShareStationIDImport } from './routes/share/$stationID'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StationsStationIDRoute = StationsStationIDImport.update({
  id: '/stations/$stationID',
  path: '/stations/$stationID',
  getParentRoute: () => rootRoute,
} as any)

const ShareStationIDRoute = ShareStationIDImport.update({
  id: '/share/$stationID',
  path: '/share/$stationID',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/share/$stationID': {
      id: '/share/$stationID'
      path: '/share/$stationID'
      fullPath: '/share/$stationID'
      preLoaderRoute: typeof ShareStationIDImport
      parentRoute: typeof rootRoute
    }
    '/stations/$stationID': {
      id: '/stations/$stationID'
      path: '/stations/$stationID'
      fullPath: '/stations/$stationID'
      preLoaderRoute: typeof StationsStationIDImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/share/$stationID': typeof ShareStationIDRoute
  '/stations/$stationID': typeof StationsStationIDRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/share/$stationID': typeof ShareStationIDRoute
  '/stations/$stationID': typeof StationsStationIDRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/share/$stationID': typeof ShareStationIDRoute
  '/stations/$stationID': typeof StationsStationIDRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/share/$stationID' | '/stations/$stationID'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/share/$stationID' | '/stations/$stationID'
  id: '__root__' | '/' | '/share/$stationID' | '/stations/$stationID'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShareStationIDRoute: typeof ShareStationIDRoute
  StationsStationIDRoute: typeof StationsStationIDRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShareStationIDRoute: ShareStationIDRoute,
  StationsStationIDRoute: StationsStationIDRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/share/$stationID",
        "/stations/$stationID"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/share/$stationID": {
      "filePath": "share/$stationID.tsx"
    },
    "/stations/$stationID": {
      "filePath": "stations/$stationID.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
